[versions]
azureFunctionsPlugin = "1.14.0"
lombok = "1.18.30"
mapstruct = "1.5.5.Final"
micronautPlugin = "4.1.2"
opencsv = "5.8"

[libraries]
azure-functions-java-library = { group = "com.microsoft.azure.functions", name = "azure-functions-java-library" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
micronaut-azure-function = { group = "io.micronaut.azure", name = "micronaut-azure-function" }
micronaut-data-azure-cosmos = { group = "io.micronaut.data", name = "micronaut-data-azure-cosmos" }
micronaut-data-document-processor = { group = "io.micronaut.data", name = "micronaut-data-document-processor" }
micronaut-http-client = { group = "io.micronaut", name = "micronaut-http-client" }
micronaut-http-validation = { group = "io.micronaut", name = "micronaut-http-validation" }
micronaut-serde-jackson = { group = "io.micronaut.serde", name = "micronaut-serde-jackson" }
micronaut-serde-processor = { group = "io.micronaut.serde", name = "micronaut-serde-processor" }
micronaut-validation = { group = "io.micronaut.validation", name = "micronaut-validation" }
micronaut-validation-processor = { group = "io.micronaut.validation", name = "micronaut-validation-processor" }
opencsv = { group = "com.opencsv", name = "opencsv", version.ref = "opencsv" }
snakeyaml = { group = "org.yaml", name = "snakeyaml" }

[plugins]
azure-functions = { id = "com.microsoft.azure.azurefunctions", version.ref = "azureFunctionsPlugin" }
micronaut = { id = "io.micronaut.application", version.ref = "micronautPlugin" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronautPlugin" }
